### ISSUE TITLE
Stripe payment dialog does not open on IOS

### ISSUE THREAD

**Issue by havard024** [ostelco/ostelco-client#9]
Stripe payment dialog does not open when you click on the buy package button.
It could be connected to that it requires an external script and that we have not specifically allowed requests to the domain where the external script is loaded from.

Also, this task will not be relevant after we fix when #8

**Comment by gavin1818** [comment]
Hi I think you may need to add the  `<allow-navigation href="*://*.stripe.com/*" />` in your config.xml. If it works, please let me know if the keyboard cant dismisses properly after the stripe payment is finished. I'm dealing with the issue now, and trying to figure out why
